### ISSUE TITLE
Style includes confuse no-missing-import/no-used-import

### ISSUE THREAD

**Issue by balloob** [Banno/polymer-lint#14]
It looks like style includes are not verified correctly and trigger a double warning: `no-unused-import` when importing the style, `no-missing-import` when including the style.

When running on [this file](https://github.com/home-assistant/home-assistant-polymer/blob/master/panels/dev-event/ha-panel-dev-event.html) I get the following warnings:

```
panels/dev-event/ha-panel-dev-event.html
  14:1   Component 'home-assistant-style' was imported but never used                no-unused-import
  20:5   Custom element 'ha-style iron-flex iron-positioning' used but not imported  no-missing-import
  57:71  Unexpected automatic binding in property 'value': {{eventType}}             no-auto-binding
  58:72  Unexpected automatic binding in property 'value': {{eventData}}             no-auto-binding
```

`home-assistant-style` is imported to provide the `ha-style` style include. I thought that the line was triggered because I forgot the import for iron-flex and iron-positioning. But adding that import (`iron-flex-layout/iron-flex-layout-classes.html`) actually triggered another warning:

```
   3:1   Component 'iron-flex-layout-classes' was imported but never used            no-unused-import
```

**Comment by ChadKillingsworth** [comment]
I'm guessing our style include doesn't handle multiple components right now. I actually didn't even know that was an option.

**Comment by ChadKillingsworth** [comment]
Also, the linter assumes that `home-assistant-style.html` provides an element named `home-assistant-style` - yours looks to be named `ha-style`. We use a strong association between filenames and component names. If the filename was `ha-style.html`, then it would be recognized (when we add the support for multiple values in the `include=` attribute).

**Comment by balloob** [comment]
Yeah I did realize that and am already fixing that 👍 

Thanks for the tool, it's giving some good feedback

**Comment by jrunning** [comment]
Thank you for your report, @balloob! Like @ChadKillingsworth said, no-missing-import and no-unused-import both rely on consistent naming between files and elements. You'll need to use the [`<!-- bplint-disable no-missing-import -->` directive](https://github.com/Banno/polymer-lint#bplint-disable) in the case of `iron-flex` and `iron-positioning` since they're defined in a file that doesn't match their names.

As for the `Custom element 'ha-style iron-flex iron-positioning' used but not imported` error, like Chad said that's because we don't currently support multiple names in style imports, but I think we should and I've created issue #16 for that.

I'm closing this, but if I've missed anything please let me know.
